# Generated by Django 2.0.10 on 2019-02-07 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancellation',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cancellation',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cancellation',
            name='removed_date',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
