# Generated by Django 2.0.10 on 2019-02-03 09:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('gender', models.IntegerField(default=1)),
                ('birth_year', models.CharField(max_length=4)),
                ('birth_month', models.CharField(max_length=2)),
                ('birth_date', models.CharField(max_length=2)),
                ('type', models.IntegerField(default=2)),
                ('status', models.IntegerField(default=1)),
            ],
        ),
    ]
