# Generated by Django 2.1.2 on 2018-11-01 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_auto_20181101_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(default=0, verbose_name='AGE'),
        ),
    ]
